// All photos and information came from: https://www.allaboutbirds.org and the birds Wikipedia pages

module.exports = [
  {
    name: 'Cerulean Warbler',
    scientificName: 'Setophaga cerulea',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/297038371-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/297039241-1280px.jpg',
    food: 'Insects',
    nesting: 'Tree',
    behavior: 'Foliage Cleaner',
    habitat: 'Forests',
    conservationStatus: 'Declining',
    region: 'The eastern half of North America and the northern region of South America',
    description: 'A warbler the color of the clear blue sky hops sky high through the upper canopy of eastern forests. That’s the male Cerulean Warbler, a brilliant blue songbird with a cerulean neck band and streaks down the sides. Females are equally well-dressed, wearing a dusky hue of blue-green.'
  },
  {
    name: 'Barn Owl',
    scientificName: 'Tyto alba',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/297342281-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/63738021-1280px.jpg',
    food: 'Mammals',
    nesting: 'Building',
    behavior: 'Aerial dive',
    habitat: 'Grasslands',
    conservationStatus: 'Low concern',
    region: 'North America below Canada',
    description: 'Barn Owls are pale overall with dark eyes. They have a mix of buff and gray on the head, back, and upperwings, and are white on the face, body, and underwings. When seen at night they can appear all white.'
  },
  {
    name: 'Northern Cardinal',
    scientificName: 'Cardinalis cardinalis',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/297087301-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/63667311-1280px.jpg',
    food: 'Seeds',
    nesting: 'Shrub',
    behavior: 'Ground Forager',
    habitat: 'Open woodlands',
    conservationStatus: 'Low concern',
    region: 'Most parts of United States east of the Rocky Mountains.',
    description: 'Male cardinals are brilliant red all over, with a reddish bill and black face immediately around the bill. Females are pale brown overall with warm reddish tinges in the wings, tail, and crest. They have the same black face and red-orange bill.'
  },
  {
    name: 'Bald Eagle',
    scientificName: 'Haliaeetus leucocephalus',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/306062281-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/60329441-1280px.jpg',
    food: 'Fish',
    nesting: 'Tree',
    behavior: 'Soaring',
    habitat: 'Forests',
    conservationStatus: 'Low Concern',
    region: 'From the Mexico border through the United States and Canada.',
    description: 'Adult Bald Eagles have white heads and tails with dark brown bodies and wings. Their legs and bills are bright yellow. Immature birds have mostly dark heads and tails; their brown wings and bodies are mottled with white in varying amounts. Young birds attain adult plumage in about five years.'
  },
  {
    name: 'American White Pelican',
    scientificName: 'Pelecanus erythrorhynchos',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/304461551-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/304461341-1280px.jpg',
    food: 'Fish',
    nesting: 'Ground',
    behavior: 'Dabbler',
    habitat: 'Wetlands',
    conservationStatus: 'Low Concern',
    region: 'Typically west of the Rocky Mountains, the Gulf States, Mexico, and Central America.',
    description: 'Adult American White Pelicans are snowy white with black flight feathers visible only when the wings are spread. A small patch of ornamental feathers on the chest can become yellow in spring. The bill and legs are yellow-orange. Immatures are mostly white as well, but the head, neck, and back are variably dusky.'
  },
  {
    name: 'American Goldfinch',
    scientificName: 'Spinus tristis',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/306710541-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/306710711-1280px.jpg',
    food: 'Seeds',
    nesting: 'Shrub',
    behavior: 'Foliage gleaner',
    habitat: 'Open woodlands',
    conservationStatus: 'Low concern',
    region: 'From mid-Alberta to North Carolina during the breeding season, and from just south of the Canada–United States border to Mexico during the winter.',
    description: 'Adult males in spring and early summer are bright yellow with black forehead, black wings with white markings, and white patches both above and beneath the tail. Adult females are duller yellow beneath, olive above. Winter birds are drab, unstreaked brown, with blackish wings and two pale wingbars.'
  },
  {
    name: 'Great Blue Heron',
    scientificName: 'Ardea herodias',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/304479371-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/60314291-1280px.jpg',
    food: 'Fish',
    nesting: 'Tree',
    behavior: 'Stalking',
    habitat: 'Marshes',
    conservationStatus: 'Low concern',
    region: 'Most of North America',
    description: 'Great Blue Herons appear blue-gray from a distance, with a wide black stripe over the eye. In flight, the upper side of the wing is two-toned: pale on the forewing and darker on the flight feathers. A pure white subspecies occurs in coastal southern Florida.'
  },
  {
    name: 'Pacific Loon',
    scientificName: 'Gavia pacifica',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/308026491-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/308033921-1280px.jpg',
    food: 'Fish',
    nesting: 'Ground',
    behavior: 'Surface dive',
    habitat: 'Wetlands',
    conservationStatus: 'Low concern',
    region: 'Northern Canada and eastern Siberia, and winters along the Pacific coast of North America.',
    description: 'Breeding adults have dove-gray heads and black upperparts marked with crisp white lines. The throat is black with sharp black-and-white lines down the sides. Crown and back of neck pale gray. The chin and throat can show a purple gloss. Eye dark red, bill and legs dark. Nonbreeding adults are dark gray-brown above with very little white feather edging; and whitish below, sometimes with a neat dark line or chinstrap across the throat. Juveniles are similar to nonbreeding adult but usually show neat pale edges to feathers.'
  },
  {
    name: 'Tufted Titmouse',
    scientificName: 'Baeolophus bicolor',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/302627281-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/302627281-1280px.jpg',
    food: 'Insects',
    nesting: 'Cavity',
    behavior: 'Foliage gleaner',
    habitat: 'Forests',
    conservationStatus: 'Low concern',
    region: 'The eastern half of North America',
    description: 'Soft silvery gray above and white below, with a rusty or peach-colored wash down the flanks. A black patch just above the bill makes the bird look snub-nosed.'
  },
  {
    name: 'Red-winged Blackbird',
    scientificName: 'Agelaius phoeniceus',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/306392131-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/63744301-1280px.jpg',
    food: 'Insects',
    nesting: 'Shrub',
    behavior: 'Ground Forager',
    habitat: 'Marshes',
    conservationStatus: 'Low concern',
    region: 'Most of North America',
    description: 'Male Red-winged Blackbirds are hard to mistake. They are an even glossy black with red-and-yellow shoulder badges. Females are crisply streaked and dark brownish overall, paler on the breast and often show a whitish eyebrow.'
  },
  {
    name: 'Scarlet Tanager',
    scientificName: 'Piranga olivacea',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/297081931-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/67449621-1280px.jpg',
    food: 'Insects',
    nesting: 'Tree',
    behavior: 'Foliage gleaner',
    habitat: 'Forests',
    conservationStatus: 'Low concern',
    region: 'East half of North America',
    description: 'In spring and summer, adult males are an unmistakable, brilliant red with black wings and tails. Females and fall immatures are olive-yellow with darker olive wings and tails. After breeding, adult males molt to female-like plumage, but with black wings and tail.'
  },
  {
    name: 'Wood Duck',
    scientificName: 'Aix sponsa',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/65533521-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/299868091-1280px.jpg',
    food: 'Plants',
    nesting: 'Cavity',
    behavior: 'Dabbler',
    habitat: 'Wetlands',
    conservationStatus: 'Low concern',
    region: 'Most of North America',
    description: 'In good light, males have a glossy green head cut with white stripes, a chestnut breast and buffy sides. In low or harsh light, they will look dark overall with paler sides. Females are gray-brown with white-speckled breast. In eclipse plumage (late summer), males lose their pale sides and bold stripes, but retain their bright eye and bill. Juveniles are very similar to females.'
  },
  {
    name: 'Long-tailed Duck',
    scientificName: 'Clangula hyemalis',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/302051251-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/302052591-1280px.jpg',
    food: 'Aquatic invertebrates',
    nesting: 'Ground',
    behavior: 'Surface dive',
    habitat: 'Wetlands',
    conservationStatus: 'Steep decline',
    region: 'The tundra and taiga regions of the arctic and winters along the northern coastlines of the Atlantic and Pacific Oceans.',
    description: 'Males in winter are mostly white and black: the head is white with a large dark patch on the neck. The breast and body are dark with white plumes covering the back. The bill is mostly black with a pink band. Males in summer are infrequently seen away from the Arctic, but are roughly the reverse of their winter plumage, with a dark head, neck, and body, and a white face patch. Females and young males are smudgy brown on the body with a white face, a brown crown and cheek patch, and a dark bill.'
  },
  {
    name: 'Ruddy Duck',
    scientificName: 'Oxyura jamaicensis',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/302124271-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/302124271-1280px.jpg',
    food: 'Aquatic invertebrates',
    nesting: 'Ground',
    behavior: 'Surface dive',
    habitat: 'Marshes',
    conservationStatus: 'Low concern',
    region: 'North American and the western coast of South America',
    description: 'Male Ruddy Ducks have blackish caps that contrast with bright white cheeks. In summer, they have rich chestnut bodies with bright blue bills. In winter, they are dull gray-brown above and paler below with dull gray bills. Females and first-year males are brownish, somewhat like winter males but with a blurry stripe across the pale cheek patch. In flight, Ruddy Ducks show solidly dark tops of the wings.'
  },
  {
    name: 'Harlequin Duck',
    scientificName: 'Histrionicus histrionicus',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/63898051-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/63898021-1280px.jpg',
    food: 'Aquatic invertebrates',
    nesting: 'Ground',
    behavior: 'Surface dive',
    habitat: 'Rivers and streams',
    conservationStatus: 'Low concern',
    region: 'The Atlantic Coast and the Pacific Coast of North America',
    description: 'Breeding male Harlequin Ducks are a spectacular slate blue with white stripes and chestnut sides. The head is elaborately marked with a white crescent in front of the eye, and chestnut highlights on the brow. Females are overall grayish-brown, with white around the bill and eye, and a neat white spot on the rear of the cheek.'
  },
  {
    name: 'American Robin',
    scientificName: 'Turdus migratorius',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/303441381-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/303441781-1280px.jpg',
    food: 'Insects',
    nesting: 'Tree',
    behavior: 'Ground forager',
    habitat: 'Open woodlands',
    conservationStatus: 'Low concern',
    region: 'Most of North America',
    description: 'American Robins are gray-brown birds with warm orange underparts and dark heads. In flight, a white patch on the lower belly and under the tail can be conspicuous. Compared with males, females have paler heads that contrast less with the gray back.'
  },
  {
    name: 'Red-crowned Parrot',
    scientificName: 'Amazona viridigenalis',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/414766991-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/414766361-1280px.jpg',
    food: 'Fruit',
    nesting: 'Cavity',
    behavior: 'Foliage gleaner',
    habitat: 'Forests',
    conservationStatus: 'Red watch list',
    region: 'They are native to a small region of northeastern Mexico and South Texas',
    description: 'Green overall, palest on the cheek, with a red crown and a bluish wash behind the cheek. The tail has a yellowish-green band; the wings show dark blue tips to flight feathers, and red secondaries. Adult female is similar but with red only on the forecrown. Juveniles are similar but have only a narrow band of red at the base of the bill.'
  },
  {
    name: 'Mute Swan',
    scientificName: 'Cygnus olor',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/59954151-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/59954111-1280px.jpg',
    food: 'Plants',
    nesting: 'Ground',
    behavior: 'Dabbler',
    habitat: 'Lakes and ponds',
    conservationStatus: 'Low concern',
    region: 'Native to Europe and eastern Asia. They can be found in North America in the Pacific Northwest and from New England south to Virginia.',
    description: 'Mute Swans are entirely white with a bill that is orange with a black base. Young swans (cygnets) may be dusky brown-gray all over, with a gray-black bill.'
  },
  {
    name: 'Tundra Swan',
    scientificName: 'Cygnus columbianus',
    imageIndex: 'https://www.allaboutbirds.org/guide/assets/photo/59956021-480px.jpg',
    imageShow: 'https://www.allaboutbirds.org/guide/assets/photo/59956011-1280px.jpg',
    food: 'Plants',
    nesting: 'Ground',
    behavior: 'Dabbler',
    habitat: 'Lakes and ponds',
    conservationStatus: 'Low concern',
    region: 'They nest in the arctic, and migrate for the winter either east to the Atlantic Flyway to the Chesapeake area, or west to California.',
    description: 'Tundra Swans have entirely white plumage. The bill is mostly black and usually has a yellow spot at the base. The legs and feet are black. Immature birds are gray-tinged on the wings, head, and neck.'
  },


]


// To add on to the seed data
// {
//   name: '',
//   scientificName: '',
//   imageIndex: '',
//   imageShow: '',
//   food: '',
//   nesting: '',
//   behavior: '',
//   habitat: '',
//   conservationStatus: '',
//   region: '',
//   description: ''
// },
